### ISSUE TITLE
Integration of Battery Indicator and placement of Bypass Capacitor

### ISSUE THREAD

**Issue by a-poorva** [a-poorva/Design-Project#5]
- Not entirely sure how to integrate the battery indicator - while I have a rough circuit for it (the different LED's shown indicate different battery ranges), would I add this before the voltage regulator and bypass capacitor, or..?
- LIttle confused about the placement of the bypass capacitor, and if one is required after the voltage regulator as well since I plan on using an Arduino Nano.

**Comment by a-poorva** [comment]
After a little research, I added a bypass capacitor to my circuit (check out Schematic v2). Would

**Comment by mlp6** [comment]
Bulk/bypass caps are always a good idea both before and after the voltage regulator; if you had to choose one, it would after so that the voltage delivered to the MCU / other parts is most stable.

W/r to the battery indicator, you would probably need to do that before the voltage regulator since after will be (hopefully) stabilized by the regulator itself.
