### ISSUE TITLE
Software Review 

### ISSUE THREAD

**Issue by a-poorva** [a-poorva/Design-Project#6]
I'm having some problems with

1. Bouncing 
I'm not sure what my program isn't accounting for. 

2. Brightness changes
The LED isn't really getting any brighter, or less? Not sure what to change in my program. Should I just assign specific values for each level of brightness and remove the if statement?

**Comment by mlp6** [comment]
It looks like you are using `digitalRead()` instead of `analogWrite()` for the PWM output in some of your case statements; am I misreading that?

W/r to the bouncing, what happens if you modulate the debounce delay?

**Comment by a-poorva** [comment]
Will fix the PWM output, thanks for catching that!

As for the debouncing, not really! It doesn't seem to make a difference.

**Comment by a-poorva** [comment]
@mlp6  I've been working with the debounce bit (toggling the delay, rewriting the code, etc.) and it just doesn't seem to work consistently. I also tried adding a capacitor across the push-button and that doesn't seem to help much either. I'm not sure where I'm going wrong here.

**Comment by mlp6** [comment]
I am not sure I totally follow how your debouncing logic should be working, but one thing I would be careful with with this line:
https://github.com/a-poorva/Design-Project/blob/8bf33d13c4cfb9eff1144b0b43db92085eee905f/Software/LEDv3.ino#L69

`ledState` is declared as an `int`; you are using it in that line more like a `bool`; can you declare it as a `bool` instead so that you can just toggle the state?  Also, I'm not a huge fan of assigning the value by flipping logical state; it would be easier to follow if you explicitly set and tested "on" and "off" states for the button.

**Comment by a-poorva** [comment]
Hi Dr. Palmeri,

So I fixed my code a little, and while it changes states smoothly when the button is pressed, the whole thing just runs on a loop continuously if left alone, not sure why. Would you mind taking a look at my code?

**Comment by mlp6** [comment]
Your `loop()` function doesn't seem to ever call `button_press()`.

**Comment by a-poorva** [comment]
Ah, thanks for catching that. However, it hasn't fixed the problem. Could it be something else?
